spring.application.name=dash

# env import
spring.config.import=optional:file:.env[.properties]

# date settings
spring.jackson.serialization.write-dates-as-timestamps=false

# db settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# jpa settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# logging settings
logging.level.org.hibernate.sql=debug

# security settings
jwt.secret=${JWT_SECRET}

# oauth ??? ?? (application-oauth.properties?? Id,????,scope ???)
spring.profiles.active=oauth

# Coolsms ??
coolsms.api-key=${COOLSMS_API_KEY}
coolsms.api-secret=${COOLSMS_API_SECRET}
coolsms.sender-number=${COOLSMS_SENDER_NUMBER}
